### ISSUE TITLE
can't get the keyboard to recognize the speaker

### ISSUE THREAD

**Issue by lesley-byte** [jpconstantineau/pykey#1]
So I installed the circuit python for the Raspberry Pi Pico because I'm assuming that's the one.  I can't get the keyboard to recognize the speaker and when I run the test code.py it comes back with:

Adafruit CircuitPython 7.0.0 on 2021-09-20; Raspberry Pi Pico with rp2040
Adafruit CircuitPython 7.0.0 on 2021-09-20; Raspberry Pi Pico with rp2040
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
AttributeError: 'module' object has no attribute 'SPEAKER'
>>> 

What did I do wrong?

**Comment by lesley-byte** [comment]
and when i comment out the buzzer it doesn't recognize that it has neopixels:

Adafruit CircuitPython 7.0.0 on 2021-09-20; Raspberry Pi Pico with rp2040
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
AttributeError: 'module' object has no attribute 'NEOPIXEL'
>>>

**Comment by jpconstantineau** [comment]
Remind me which board you got?

there are a few boards that I am targeting and getting the right circuit python download is the first step, followed by the firmware

**Comment by lesley-byte** [comment]
I think everything but the 'i' key is registering now.  I'm going to see if its a faulty switch

**Comment by lesley-byte** [comment]
No sandy-ness. It actually looks great. I think it was just the one spot.  This is a great product.
